# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - export PROJECT_NAME="fitex-server" # or set via settings/ci_cd/#Variables
  - export YB_REGISTRY_USER="fitex" # or set via settings/ci_cd/#Variables
  - export YB_REGISTRY_PASSWORD="Fitex.&*" # or set via settings/ci_cd/#Variables
  - export YB_REGISTRY=hub.yottab.io
  - export YB_REGISTRY_IMAGE="$YB_REGISTRY/$YB_REGISTRY_USER/$PROJECT_NAME"  # or set predifined $CI_PROJECT_NAME instead of $PROJECT_NAME
  - docker login -u "$YB_REGISTRY_USER" -p "$YB_REGISTRY_PASSWORD" "$YB_REGISTRY"

build-master:
  stage: build
  script:
    - docker build --pull -t "$YB_REGISTRY_IMAGE" .
    - docker push "$YB_REGISTRY_IMAGE"
  only:
    - master

build-tags:
  stage: build
  script:
    - docker build --pull -t "$YB_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$YB_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v.*$/
